os: linux
dist: bionic
language: php

before_install:
  - composer global require "fxp/composer-asset-plugin:~1.4.6"

addons:
  apt:
    update: true

script:
  - echo "Building"
  - composer install --no-dev --ignore-platform-reqs -o -q
  - mv dev_node_modules node_modules || true
  - npm i
  - npm run build
  - mv node_modules dev_node_modules
  - mv prod_node_modules node_modules || true
  - npm i --production

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master