os: linux
dist: bionic
language: php

before_install:
  - composer global require "fxp/composer-asset-plugin:~1.4.6"

addons:
  apt:
    update: true

script:
  - echo "Building"
  - composer install --no-dev --ignore-platform-reqs -o -q
  - npm i
  - npm run build
  - rm -rf node_modules
  - npm i --production


before_deploy:
  - openssl aes-256-cbc -K $encrypted_99cde466f782_key -iv $encrypted_99cde466f782_iv -in travis-openssh-pk.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - ssh -o StrictHostKeyChecking=no -l "$SSH_USER" "$SSH_HOST"

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master