dist: bionic
language: php

script:
  - echo "hello world"
  - touch test.txt
  - echo "Hello world" >> test.txt
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master